# Generated by Django 3.2.13 on 2023-11-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pfp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pfp',
        ),
    ]
