# Generated by Django 3.2.13 on 2023-11-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20231119_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default_pfp.jpg', upload_to='profile_pics/'),
        ),
    ]
