# Generated by Django 3.2.13 on 2023-11-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20231119_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/static/img/pfp/user.png', upload_to='profile_pics'),
        ),
    ]
